window.gfxItemID = function(i) {
    var itemMap = {
        // Travel Items
        "Aa": "Travel Boots",
        "Ab": "Hiking Boots",
        "Ac": "Swamp Boots",
        "Ad": "Mountain Boots",
        "Ae": "Lava Boots",
        "Af": "Row Boat",

        // Tools / Utilities
        "Ba": "Pick Axe",
        "Bb": "Wood Axe",
        "Bc": "Net",
        "Bd": "Fishing Pole",
        "Be": "Lantern",
        "Bf": "Wand",

        // Game Items
        "Ca": "Bucket",
        "Cb": "Bucket of Water",
        "Cc": "Bucket of Milk",
        "Cd": "Bucket of Mud",
        "Ce": "Log",
        "Cf": "Blue Key",
        "Cg": "Red Key",
        "Ch": "Crystal Key",
        "Ci": "Treasure Chest",

        // Stacked Items
        "Ea": "Match",
        "Eb": "Matches",
        "Ec": "Matches",
        "Ed": "Feathers",
        "Ee": "Arrowheads",
        "Ef": "Arrows",
        "Eg": "Potion x1",
        "Eh": "Potion x2",
        "Ei": "Potion x3",
        "Ej": "Potion x1",
        "Ek": "Potion x2",
        "El": "Potion x3",

        // Food
        "Fa": "Cheese",
        "Fb": "Egg",
        "Fc": "Dragon Egg",
        "Fd": "Wheat",
        "Fe": "Flour",
        "Ff": "Dough",
        "Fg": "Raw Pizza",

        // Plant Foods
        "Ga": "Plant",
        "Gb": "Tomato",
        "Gc": "Tomatos",
        "Gd": "Tamatos",
        "Ge": "Tomatoes",
        "Gf": "Letcue",

        // Cooked Foods
        "Ha": "Bread",
        "Hb": "Slice of Pizza",
        "Hc": "Half Pizza",
        "Hd": "Most of a Pizza",
        "He": "Pizza",
        "Hf": "Half Sandwich",
        "Hg": "Sandwich",
        "Hp": "Qandy",

        // Raw Fish
        "Ia": "Raw Crab",
        "Ic": "Raw Carp",
        "Ie": "Raw Catfish",
        "Ig": "Raw Flounder",
        "Ii": "Raw Lobster",
        "Ik": "Raw Shark",
        "Il": "Raw Ham",
        "Im": "Raw Crawler",
        "In": "Raw Crawler",

        // Cooked Fish
        "Ja": "Crab",
        "Jc": "Carp",
        "Je": "Catfish",
        "Jg": "Flounder",
        "Ji": "Lobster",
        "Jk": "Shark",
        "Jl": "Ham",
        "Jm": "Crawler",
        "Jn": "Crawler",

        // Mining Items
        "Ka": "Copper Ore",
        "Kc": "Tin Ore",
        "Kd": "Emerald",
        "Ke": "Iron Ore",
        "Kg": "Coal",
        "Kh": "Ruby",
        "Ki": "Lava Ore",
        "Kk": "Diamond",

        // Hats
        "La": "Black Hat",
        "Lb": "White Hat",
        "Lc": "Pink Hat",
        "Ld": "Blue Hat",
        "Lf": "Red Bandana",
        "Lg": "Blue Bandana",
        "Lk": "Cylon Helm",
        "Ll": "Cylon Helm",

        // Weapons
        "Ma": "Sword",
        "Mk": "Shield",

        // Enemies
        "Pa": "Spider",
        "Pb": "Mosquito",
        "Pc": "Scorpion",
        "Pd": "Fire Ant",

        // Player Items
        "Sa": "Black Team",
        "Sb": "White Team",
        "Sc": "Pink Team",
        "Sd": "Blue Team",
        "Se": "Black Flag",
        "Sf": "White Flag",
        "Sg": "Pink Flag",
        "Sh": "Blue Flag",

        // Buildings (32px+)
        "Ta": "City",
        "Tb": "Cart",
        "Tc": "Fernace",
        "Td": "Magic Guild",
        "Te": "Building",
        "Tf": "Building",
        "Tg": "Building",
        "Th": "Building",
        "Ti": "Hut",
        "Tj": "Flag Pole",
        "Tk": "Building",
        "Tl": "Pyramid",
        "Tm": "Ruins",
        "Tn": "Fountain",
        "To": "Bunker",
        "Tp": "Dead Tree",

        // Structures
        "Ua": "Stove",
        "Ub": "Fishing Guild",
        "Uc": "Statue",
        "Ud": "Tower",
        "Ue": "Windmill",
        "Uf": "Tower",
        "Ug": "Grand Tree",
        "Uh": "Throne",
        "Ui": "Door",
        "Uj": "Grand Tree",
        "Uk": "Red Gate",
        "Ul": "Blue Gate",

        // UI / Verb Commands
        "Va": "$$-- set avatar string",
        "Vb": "Vb",
        "Vc": "##enter city",
        "Vd": "$$[drop/get] ",
        "Ve": "East",
        "Vf": "Vf",
        "Vg": "Vg",
        "Vh": "Vh",
        "Vi": "inventory",
        "Vj": "Vj",
        "Vk": "Vk",
        "Vl": "Look",
        "Vm": "$$##[make item/remove item] at ",
        "Vn": "North",
        "Vo": "Vo",
        "Vp": "Vp",
        "Vq": "Vq",
        "Vr": "$$##remove object at ",
        "Vs": "South",
        "Vt": "%%## teleport to ",
        "Vu": "Vu",
        "Vv": "Vv",
        "Vw": "West",
        "Vx": "Vx",
        "Vy": "Vy",
        "Vz": "Vz",
        "V1": "V1",
        "V2": "V2",
        "V3": "V3",
        "V4": "V4",
        "V5": "V5",
        "V6": "V6",
        "V7": "V7",
        "V8": "V8",
        "V9": "V9",

        // Registers
        "Wa": "## Wa",
        "Wb": "## Wb",
        "Wc": "## Wc",
        "Wd": "## Wd",
        "We": "## We",
        "Wf": "## Wf",
        "Wg": "## Wg",
        "Wh": "## Wh",
        "Wi": "## Wi",
        "Wj": "## Wj",
        "Wk": "## Wk",
        "Wl": "## Wl",
        "Wm": "## Wm",
        "Wn": "## Wn",
        "Wo": "## Wo",
        "Wp": "## Wp",
        "Wq": "## Wq",
        "Wr": "## Wr",
        "Ws": "## Ws",
        "Wt": "## Wt",
        "Wu": "## Wu",
        "Wv": "## Wv",
        "Ww": "## Ww",
        "Wx": "## Wx",
        "Wy": "## Wy",
        "Wz": "## Wz",
        "W0": "%% spawn player on sector",
        "W1": "%% spawn player z-location",
        "W2": "%% player counter",
        "W3": "%% player counter carry",
        "W4": "%% W4",
        "W5": "%% W5",
        "W6": "%% W6",
        "W7": "%% W7",
        "W8": "%% W8",
        "W9": "%% W9",

        // Logic / Scripting
        "Xa": "$$ Request unique player-id",
        "Xb": "Xb",
        "Xc": "close switch.",
        "Xd": "$$## set to dice roll from value to ",
        "Xe": "$$##[if equal/if not equal] ",
        "Xf": "Xf",
        "Xg": "Xg",
        "Xh": "Xh",
        "Xi": "$$[if inventory has/if inventory does not have]",
        "Xj": "Xj",
        "Xk": "Xk",
        "Xl": "$$##[if  less than/if greater than]",
        "Xm": "$$##[math plus/math minus]",
        "Xn": "NOT",
        "Xo": "Xo",
        "Xp": "Xp",
        "Xq": "Xq",
        "Xr": "$$$$ replace inventory item",
        "Xs": "$$##set to ",
        "Xt": "Xt",
        "Xu": "Xu",
        "Xv": "Xv",
        "Xw": "Xw",
        "Xx": "Xx",
        "Xy": "Xy",
        "Xz": "Xz",
        "X0": "X0",
        "X1": "X1",
        "X2": "X2",
        "X3": "X3",
        "X4": "X4",
        "X5": "X5",
        "X6": "X6",
        "X7": "X7",
        "X8": "X8",
        "X9": "X9",

        // Game States / Actions
        "Za": "Nothing",
        "Zb": "NO",
        "Zc": "Switch Off",
        "Zd": "Switch On",
        "Ze": "Teleport",
        "Zf": "Sign",
        "Zg": "Pier",
        "Zh": "Well",
        "Zi": "Fire Pit",
        "Zj": "Fire",
        "Zk": "Mysterious Man",
        "Zl": "Mountain Hideout",
        "Zm": "City Gates",
        "Zn": "Green",
        "Zo": "Table",
        "Zp": "Terrain",
        "Zq": "Pipe",
        "Zr": "Pipe",
        "Zs": "Table",

    };

    return itemMap[i] || "Unknown"; // Use bracket notation to access properties
};
