window.gfxItemID = function(i) {
    var itemMap = {
        // Travel Items
        "Aa": "Travel Boots",
        "Ab": "Hiking Boots",
        "Ac": "Swamp Boots",
        "Ad": "Mountain Boots",
        "Ae": "Lava Boots",
        "Af": "Row Boat",

        // Tools/Utilities
        "Ba": "Pick Axe",
        "Bb": "Wood Axe",
        "Bc": "Net",
        "Bd": "Fishing Pole",
        "Be": "Lantern",
        "Bf": "Wand",

        // Game Items
        "Ca": "Bucket",
        "Cb": "Bucket of Water",
        "Cc": "Bucket of Milk",
        "Cd": "Bucket of Mud",
        "Ce": "Log",
        "Cf": "Blue Key",
        "Cg": "Red Key",
        "Ch": "Crystal Key",
        "Ci": "Treasure Chest",
 
        // Qujest Items

        // Stacked Items
        "Ea": "Match",
        "Eb": "Matches",
        "Ec": "Matches",
        "Ed": "Feathers",
        "Ee": "Arrowheads",
        "Ef": "Arrows",
        "Eg": "Potion x1",
        "Eh": "Potion x2",
        "Ei": "Potion x3",
        "Ej": "Potion x1",
        "Ek": "Potion x2",
        "El": "Potion x3",

        // Food
        "Fa": "Cheese",
        "Fb": "Egg",
        "Fc": "Dragon Egg",
        "Fd": "Wheat",
        "Fe": "Flour",
        "Ff": "Dough",
        "Fg": "Raw Pizza",

        // Plant Foods
        "Ka": "Plant",
        "Gb": "Tomato",
        "Gc": "Tomatos",
        "Gd": "Tamatos",
        "Ge": "Tomatoes",
        "Gf": "Letcue",

        // Food
        "Hf": "Bread",
        "Hf": "Slice Pizza",
        "Hf": "Half Pizza",
        "Hf": "Pizza",
        "Hf": "Pizza",
        "Hf": "Half Sandwich",
        "Hf": "Sandwich",

        // Raw Fish
        "Ia": "Raw Crab",
        "Ic": "Raw Carp",
        "Ie": "Raw Catfish",
        "Ig": "Raw Flounder",
        "Ii": "Raw Lobster",
        "Ik": "Raw Shark",
        "Im": "Raw Crawler",
        "In": "Raw Crawler",
        "Ip": "Raw Frog Legs",
        "Iq": "Raw Ham",

        // Cooked Fish
        "Ja": "Crab",
        "Jc": "Carp",
        "Je": "Catfish",
        "Jg": "Flounder",
        "Ji": "Lobster",
        "Jk": "Shark",
        "Jm": "Crawler",
        "Jn": "Crawler",
        "Jp": "Legs",
        "Jq": "Ham",

        // Mining Items
        "Ka": "Copper Ore",
        "Kc": "Tin Ore",
        "Kd": "Emerald",
        "Ke": "Iron Ore",
        "Kg": "Coal",
        "Kh": "Ruby",
        "Ki": "Lava Ore",
        "Kk": "Diamond",

        // Hats
        "La": "White Hat",
        "Lb": "Black Hat",
        "Lc": "Blue Hat",
        "Ld": "Red Hat",
        "Ld": "Red Bandana",
        "Le": "Blue Bandana",
        "Lf": "Mask",
        "Lk": "Cylon Helm",
        "Ll": "Cylon Helm",

        // Swords
        "Ma": "Sword",

        // Shields
        "Mk": "Shield",

        // Enemies
        "Pa": "Spider",
        "Pb": "Mosquito",
        "Pc": "Scorpion",
        "Pd": "Fire Ant",

        // Player Items
        "Sa": "White Team",
        "Sb": "Black Team",
        "Sc": "Pink Team",
        "Sd": "Blue Team",
        "Se": "White Flag",
        "Sf": "Black Flag",
        "Sg": "Pink Flag",
        "Sh": "Blue Flag",
        
        // Static Objects/Buildings, can be larger than 32x32 px
        "Ta": "City",
        "Tb": "Cart",
        "Tc": "Fernace",
        "Td": "Magic Guild",
        "Te": "Building",
        "Tf": "Building",
        "Tg": "Building",
        "Th": "Building",
        "Ti": "Hut",
        "Tj": "Flag Pole",
        "Tk": "Building",
        "Tl": "Pyramid",
        "Tm": "Ruins",
        "Tn": "Fountain",
        "To": "Bunker",
        "Tp": "Dead Tree",
        "Ua": "Stove",
        "Ub": "Tavern",
        "Uc": "Windmill",
        "Ud": "Tower",
        "Ue": "Temple",
        "Uf": "Throne",
        "Ug": "Grand Tree",

        // UI/Verb Commands (These definitely seem like a different category than physical items)
        "Va": "$$--[get unique player it/set avatar]",
        "Vb": "Vb",
        "Vc": "Vc",
        "Vd": "$$[drop item/get item] ",
        "Ve": "East",
        "Vf": "Vf",
        "Vg": "Vg",
        "Vh": "Vh",
        "Vi": "Inventory",
        "Vj": "Vj",
        "Vk": "Vk",
        "Vl": "Look",
        "Vm": "$$##[make item/remove item] ",
        "Vn": "North",
        "Vo": "Vo",
        "Vp": "Vp",
        "Vq": "Vq",
        "Vr": "$$##remove object ",
        "Vs": "South",
        "Vt": "%%## teleport to ",
        "Vu": "Vu",
        "Vv": "Vv",
        "Vw": "West",
        "Vx": "Vx",
        "Vy": "Vy",
        "Vz": "Vz",
        "V1": "V1",
        "V2": "V2",
        "V3": "V3",
        "V4": "V4",
        "V5": "V5",
        "V6": "V6",
        "V7": "V7",
        "V8": "V8",
        "V9": "V9",

        // Registers 
        "Wa": "##",
        "Wb": "##",
        "Wc": "##",
        "Wd": "Wd##",
        "We": "We##",
        "Wf": "Wf##",
        "Wg": "Wg##",
        "Wh": "Wh##",
        "Wi": "Wi##",
        "Wj": "Wj##",
        "Wk": "Wk##",
        "Wl": "Wl##",
        "Wm": "##Wm",
        "Wn": "Wn##",
        "Wo": "Wo##",
        "Wp": "Wp##",
        "Wq": "Wq##",
        "Wr": "Wr##",
        "Ws": "Ws##",
        "Wt": "Wt##",
        "Wu": "Wu##",
        "Wv": "Wv##",
        "Ww": "Ww##",
        "Wx": "Wx##",
        "Wy": "Wy##",
        "Wz": "Wz##",
        "W1": "W1##",
        "W2": "W2##",
        "W3": "W3##",
        "W4": "W4##",
        "W5": "W5##",
        "W6": "W6##",
        "W7": "W7##",
        "W8": "W8##",
        "W9": "W9##",
        "W0": "W0##",

        // Logic/Scripting Commands
        "Xa": "Xa",
        "Xb": "Xb",
        "Xc": "clear gate",
        "Xd": "Xd",
        "Xe": "Xe",
        "Xf": "Xf",
        "Xg": "Xg",
        "Xh": "Xh",
        "Xi": "$$[if/if not] inventory ",
        "Xj": "Xj",
        "Xk": "Xk",
        "Xl": "Xl",
        "Xm": "Xm",
        "Xn": "NOT",
        "Xo": "Xo",
        "Xp": "Xp",
        "Xq": "Xq",
        "Xr": "$$[remove/add] inventory",
        "Xs": "Xs",
        "Xt": "Xt",
        "Xu": "Xu",
        "Xv": "Xv",
        "Xw": "Xw",
        "Xx": "Xx",
        "Xy": "Xy",
        "Xz": "Xz",
        "X1": "X1",
        "X2": "X2",
        "X3": "X3",
        "X4": "X4",
        "X5": "X5",
        "X6": "X6",
        "X7": "X7",
        "X8": "X8",
        "X9": "X9",
        "X0": "X0",

        // Game States/Actions/Environmental 
        "Za": "Nothing",
        "Zb": "NO",
        "Zc": "Switch Off",
        "Zd": "Switch On",
        "Ze": "Teleport",
        "Zf": "Sign",
        "Zg": "Pier",
        "Zh": "Well",
        "Zi": "Fire Pit",
        "Zj": "Fire",
        "Zk": "Mysterious Man",
        "Zl": "Mountain Hideout",
        "Zm": "City Gates",
        "Zn": "Green",
        "Zo": "Red",
        "Zo": "Terrain",
        "Zo": "Pipe",
        "Zo": "Pipe",
        "Zo": "Table"

    };

    return itemMap[i] || "Unknown"; // Use bracket notation to access properties
};
