window.gfxItemID = function(i) {
    var itemMap = {
        "Bd": "Bucket",
        "Cg": "Log",
        "El": "Bucket Water",
        "Jc": "Qandy",
        "La": "Black Hat",
        // Player Items
        "Sa": "Player Sa",
        "Sb": "Player Sb",
        "Sc": "Player Sc",
        "Sd": "Player Sd",
        "Se": "Player Se",
        "Sf": "Player Sf",
        "Sg": "Player Sg",
        "Sh": "Player Sh",
        "Ta": "Player Ta",
        "Tb": "Player Tb",
        "Tc": "Player Tc",
        "Td": "Player Td",
        "Te": "Player Te",
        "Tf": "Player Tf",
        "Tg": "Player Tg",
        "Th": "Player Th",

        // Verb Commands
        "Va": "Avatar",
        "Vb": "Vb",
        "Vc": "Vc",
        "Vd": "Vd",
        "Ve": "East",
        "Vf": "Vf",
        "Vg": "Vg",
        "Vh": "Vh",
        "Vi": "Inventory",
        "Vj": "Vj",
        "Vk": "Vk",
        "Vl": "Look",
        "Vm": "Vm",
        "Vn": "North",
        "Vo": "Vo",
        "Vp": "Vp",
        "Vq": "Vq",
        "Vr": "Vr",
        "Vs": "South",
        "Vt": "%%$$ teleport to ",
        "Vu": "Vu",
        "Vv": "Vv",
        "Vw": "West",
        "Vx": "Vx",
        "Vy": "Vy",
        "Vz": "Vz",
        "V1": "V1",
        "V2": "V2",
        "V3": "V3",
        "V4": "V4",
        "V5": "V5",
        "V6": "V6",
        "V7": "V7",
        "V8": "V8",
        "V9": "V9",

        // Registers 
        "Wa": "Wa",
        "Wb": "Wb",
        "Wc": "Wc",
        "Wd": "Wd",
        "We": "We",
        "Wf": "Wf",
        "Wg": "Wg",
        "Wh": "Wh",
        "Wi": "Wi",
        "Wj": "Wj",
        "Wk": "Wk",
        "Wl": "Wl",
        "Wm": "Wm",
        "Wn": "Wn",
        "Wo": "Wo",
        "Wp": "Wp",
        "Wq": "Wq",
        "Wr": "Wr",
        "Ws": "Ws",
        "Wt": "Wt",
        "Wu": "Wu",
        "Wv": "Wv",
        "Ww": "Ww",
        "Wx": "Wx",
        "Wy": "Wy",
        "Wz": "Wz",
        "W1": "W1",
        "W2": "W2",
        "W3": "W3",
        "W4": "W4",
        "W5": "W5",
        "W6": "W6",
        "W7": "W7",
        "W8": "W8",
        "W9": "W9",
        "W0": "W0",

        // Logic Gates
        "Xa": "Xa",
        "Xb": "Xb",
        "Xc": "clear gate",
        "Xd": "Xd",
        "Xe": "Xe",
        "Xf": "Xf",
        "Xg": "Xg",
        "Xh": "Xh",
        "Xi": "$$if inventory",
        "Xj": "Xj",
        "Xk": "Xk",
        "Xl": "Xl",
        "Xm": "Xm",
        "Xn": "NOT",
        "Xo": "Xo",
        "Xp": "Xp",
        "Xq": "Xq",
        "Xr": "Xr",
        "Xs": "Xs",
        "Xt": "Xt",
        "Xu": "Xu",
        "Xv": "Xv",
        "Xw": "Xw",
        "Xx": "Xx",
        "Xy": "Xy",
        "Xz": "Xz",
        "X1": "X1",
        "X2": "X2",
        "X3": "X3",
        "X4": "X4",
        "X5": "X5",
        "X6": "X6",
        "X7": "X7",
        "X8": "X8",
        "X9": "X9",
        "X0": "X0",

        // Static Objects/Buildings
        "Yj": "Flag Pole",

        // Game States/Actions/Environmental 
        "Za": "Nothing",
        "Zb": "NO",
        "Ze": "Teleport",
        "Zf": "Sign",
        "Zh": "Well",
        "Zi": "Fire Pit",
        "Zj": "Fire",
    };

    return itemMap[i] || "Unknown"; // Use bracket notation to access properties
};
